### ISSUE TITLE
The starts_in sensor is incorrect when loadshedding is the following day

### ISSUE THREAD

**Issue by boozelclark** [wernerhp/ha.integration.load_shedding#34]
The starts in sensor only looks at times so it gives an incorrect value in the low stages of loadshedding when an areas next slot is the following day. The delta calculation needs to be between the two datetimes and not just the times.

**Comment by wernerhp** [comment]
Is this the `starts_in` in the sensor attributes or the Card's yaml?

**Comment by boozelclark** [comment]
I think it's both. It may not actually be if the next slot is not the following day but if it is more than 24 hours away. I'll try and replicate this next time my loadshedding schedule is in that state and share more accurate details

**Comment by wernerhp** [comment]
The issue is with `.seconds` which should be `.total_seconds() | int`.  

Made some tweaks.  Let me know if this works.

![image](https://user-images.githubusercontent.com/2578772/200041753-bd0ee58f-2bf1-4f3d-bdf2-834a275de223.png)
![image](https://user-images.githubusercontent.com/2578772/200041874-e45f6263-ff36-4cfe-91db-1a453454766a.png)
![image](https://user-images.githubusercontent.com/2578772/200041978-69a0aba3-c847-4cdc-8884-18de9d0baf71.png)
![image](https://user-images.githubusercontent.com/2578772/200042148-9abc883c-b479-4990-b7a4-e58e1638b7b9.png)

<details>
<summary>Code</summary>

```yaml
type: 'markdown'
content: >
  {% set stage_sensor = "sensor.load_shedding_stage_eskom" %} 
  {% set area_sensor = "sensor.load_shedding_area_eskde_14_milnertoncityofcapetownwesterncape" %}
  {% set start_time = state_attr(stage_sensor, "start_time") %}   
  {% set end_time = state_attr(stage_sensor, "end_time") %}
  {% set area_schedule = state_attr(area_sensor, "forecast") %} 

  {% if area_schedule %}
    {% set start_time = area_schedule[0].start_time %}
    {% set end_time = area_schedule[0].end_time %}
    
    {% if is_state(area_sensor, "off") %}
      {% set starts_in = timedelta(minutes=state_attr(area_sensor, "starts_in")).total_seconds() | int // 60 %}
      {% set mins = starts_in % 60 %}
      {% set hrs = starts_in // 60 % 24 %}
      {% set days = starts_in // 1440 %}
      {% set alert = "Load Shedding starts in {d}d {h}h {m}m ({next})".format(d=days, m=mins, h=hrs, next=as_timestamp(start_time) | timestamp_custom("%H:%M", True)) %} 

      {% if is_state_attr(stage_sensor, "stage", 0) %}
        <ha-alert alert-type="success">{{ states(stage_sensor) }}</ha-alert>
      {% elif starts_in > 1440  %}
        <ha-alert alert-type="success">{{ alert }}</ha-alert>
      {% elif not is_state_attr(stage_sensor, "stage", 0) and 60 < starts_in <= 1440 %}
        <ha-alert alert-type="warning">{{ alert }}</ha-alert>
      {% else %}
        <ha-alert alert-type="error">{{ alert }}</ha-alert>
      {% endif %}
    {% else %}
      {% set ends_in = timedelta(minutes=state_attr(area_sensor, "ends_in")).total_seconds() | int // 60 %}   
        {% set mins = ends_in % 60 %}        
        {% set hrs = ends_in // 60 % 24 %}
        {% set days = ends_in // 1440 %}
        {% set alert = "Load Shedding ends in {d}d {h}h {m}m ({next})".format(d=days, m=mins, h=hrs, next=as_timestamp(end_time) | timestamp_custom("%H:%M", True)) %} 

        <ha-alert alert-type="error">{{ alert }}</ha-alert>
    {% endif %}
  {% endif %}
```
</details>

I'd also recommend you check out the [latest dev release](https://github.com/wernerhp/ha.integration.load_shedding/releases/tag/v1.1.0-dev.1) for a new card.
<img src="https://user-images.githubusercontent.com/2578772/200029575-18b89e78-fffb-4307-b3ea-63e5c7055b98.png" width="50%"/>

**Comment by wernerhp** [comment]
Fixed `card4.yaml` in [v1.1.0-dev.2](https://github.com/wernerhp/ha.integration.load_shedding/releases/tag/v1.1.0-dev.2)
